### ISSUE TITLE
Framework Binary is missing armv7

### ISSUE THREAD

**Issue by chbeer** [doo/scanbot-sdk-ios-spm#1]
Architectures in the fat file: /…/Debug-iphoneos/ScanbotSDK.framework/ScanbotSDK are: arm64

Standard architectures of Xcode are still arm64 and armv7.

**Comment by sebastato** [comment]
Hi chbeer, 
for technical and practical reasons the deployment target of our SDK is iOS 11.0. Older versions are not supported. 
Since iOS 11 and later operating systems do not support any of the 32-bit devices, we decided to drop the the 32-bit armv7 architecture from our SDKs. We simply see no sense in bloating up our frameworks with useless binaries.
Thanks for your understanding. Please let us know, if you need further assistance with our SDK.
